---
title: "Lab3A"
author: "Margaret Hilliard"
date: "9/7/2020"
output: html_document
bibliography: /Users/margarethilliard/Desktop/Evolutionary_Genomics/genomics-course/data/references.bib
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, eval = FALSE)

```
# Starting with data and data structure 
```{r}
# load the tidyverse library 
library(tidyverse)
# download the raw data and call it "surveys" 
download.file(url = "https://ndownloader.figshare.com/files/2292169",
              destfile = "data_raw/portal_data_joined.csv")

surveys <- read.csv("data_raw/portal_data_joined.csv")

# display raw data 
head(surveys)
View(surveys)

# examine the structure of the data 
str(surveys)
```
# Challenge 1
```{r}
# Based on the output of str(surveys), can you answer the following questions?
   # What is the class of the object surveys?
class(surveys)
   # How many rows and how many columns are in this object?
nrow(surveys)
ncol(surveys)
   # How many species have been recorded during these surveys?
unique_species<- unique(surveys$species_id)
length(unique_species)
```
# Indexing and subsetting dataframes 
```{r}
# first element in the first column of the data frame (as a vector)
surveys[1, 1]   
# first element in the 6th column (as a vector)
surveys[1, 6]   
# first column of the data frame (as a vector)
surveys[, 1]    
# first column of the data frame (as a data.frame)
surveys[1]      
# first three elements in the 7th column (as a vector)
surveys[1:3, 7] 
# the 3rd row of the data frame (as a data.frame)
surveys[3, ]    
# equivalent to head_surveys <- head(surveys)
head_surveys <- surveys[1:6, ] 

# exclude certain indices of a data frame using the “-” sign:

surveys[, -1]          # The whole data frame, except the first column
surveys[-(7:34786), ] # Equivalent to head(surveys)

# subset by calling indices by calling their column names directly:
surveys["species_id"]       # Result is a data.frame
surveys[, "species_id"]     # Result is a vector
surveys[["species_id"]]     # Result is a vector
surveys$species_id          # Result is a vector
```
# Challenge 2
```{r}
# challenge: Create a data.frame (surveys_200) containing only the data in row 200 of the surveys dataset.
surveys_200 <- data.frame(surveys["200", ] ) 

nrow(surveys)
n_rows <- nrow(surveys)
# Create a new data frame (surveys_last) from that last row
surveys_last <- surveys[n_rows, ]
# Use nrow() to extract the row that is in the middle of the data frame. Store the content of this row in an object named surveys_middle
survey_middle <- surveys[n_rows/2, ]
# Combine nrow() with the - notation above to reproduce the behavior of head(surveys), keeping just the first through 6th rows of the surveys dataset
surveys_head <- surveys[-(7:n_rows), ]
surveys_head
head(surveys)
```
# Factors 
```{r}
# Factors represent categorical data. They are stored as integers associated with labels and they can be ordered or unordered. While factors look (and often behave) like character vectors, they are actually treated as integer vectors by R. So you need to be very careful when treating them as strings.
# Once created, factors can only contain a pre-defined set of values, known as levels. By default, R always sorts levels in alphabetical order. For instance, if you have a factor with 2 levels:
sex <- factor(c("male", "female", "female", "male"))
levels(sex)
nlevels(sex)
sex # current order
sex <- factor(sex, levels = c("male", "female"))
sex # after re-ordering
```
# Converting factors 
```{r}
# convert a factor to a character vector
as.character(sex)

# convert factors where the levels appear as numbers
# compare: 
year_fct <- factor(c(1990, 1983, 1977, 1998, 1990))
as.numeric(year_fct)               # Wrong! And there is no warning...
as.numeric(as.character(year_fct)) # Works...
as.numeric(levels(year_fct))[year_fct]    # The recommended way.

# Notice that in the levels() approach, three important steps occur:
    # We obtain all the factor levels using levels(year_fct)
    # We convert these levels to numeric values using as.numeric(levels(year_fct))
   # We then access these numeric values using the underlying integers of the vector year_fct inside the square brackets

```
# Renaming factors
```{r}
## bar plot of the number of females and males captured during the experiment:
plot(as.factor(surveys$sex))

# pull out the data on sex and work with that data, so we’re not modifying the working copy of the data frame:
sex<- factor(surveys$sex)
head(sex)
levels(sex)
levels(sex)[1] <- "undetermined"
levels(sex)
head(sex)
```
# Challenge 3
```{r}
# Rename “F” and “M” to “female” and “male” respectively.
levels(sex)
levels(sex)[2] <- "female"
levels(sex)[3] <- "male"
levels(sex)
sex <- factor(sex, levels = c("female", "male", "undetermined"))
plot(as.factor(sex))
```
# Using stringsAsFactors = FALSE
```{r}
## Compare the difference between our data read as `factor` vs `character`.
surveys <- read.csv("data_raw/portal_data_joined.csv", stringsAsFactors = TRUE)
str(surveys)
surveys <- read.csv("data_raw/portal_data_joined.csv", stringsAsFactors = FALSE)
str(surveys)
## Convert the column "plot_type" into a factor
surveys$plot_type <- factor(surveys$plot_type)
```
# Challenge 4
```{r}
# 1. We have seen how data frames are created when using read.csv(), but they can also be created by hand with the data.frame() function. There are a few mistakes in this hand-crafted data.frame. Can you spot and fix them? Don’t hesitate to experiment!
# animal_data <- data.frame(
#          animal = c(dog, cat, sea cucumber, sea urchin),
#          feel = c("furry", "squishy", "spiny"),
#          weight = c(45, 8 1.1, 0.8)
#          )
animal_data <- data.frame(
          animal = c("dog", "cat", "sea cucumber", "sea urchin"),
          feel = c("furry", "soft", "squishy", "spiny"),
          weight = c(45, 8, 1.1, 0.8)
          )
animal_data

# 2. Can you predict the class for each of the columns in the following example? Check your guesses using str(country_climate): 
    # Are they what you expected? Why? Why not?
country_climate <- data.frame(
       country = c("Canada", "Panama", "South Africa", "Australia"),
       climate = c("cold", "hot", "temperate", "hot/temperate"),
       temperature = c(10, 30, 18, "15"),
       northern_hemisphere = c(TRUE, TRUE, FALSE, "FALSE"),
       has_kangaroo = c(FALSE, FALSE, FALSE, 1)
       )
str(country_climate)
class(country_climate$temperature) # would expect this to be numeric 
   
 # What would have been different if we had added stringsAsFactors = FALSE when creating the data frame?
country_climate <- data.frame(
       country = c("Canada", "Panama", "South Africa", "Australia"),
       climate = c("cold", "hot", "temperate", "hot/temperate"),
       temperature = c(10, 30, 18, "15"),
       northern_hemisphere = c(TRUE, TRUE, FALSE, "FALSE"),
       has_kangaroo = c(FALSE, FALSE, FALSE, 1), stringsAsFactors = FALSE
       )
str(country_climate)
class(country_climate$temperature)
    # What would you need to change to ensure that each column had the accurate data type? 

#removing the quotes in temperature and northern_hemisphere and replacing 1 by TRUE in the has_kangaroo column would give what was probably intended
country_climate <- data.frame(
       country = c("Canada", "Panama", "South Africa", "Australia"),
       climate = c("cold", "hot", "temperate", "hot/temperate"),
       temperature = c(10, 30, 18, 15),
       northern_hemisphere = c(TRUE, TRUE, FALSE, FALSE),
       has_kangaroo = c(FALSE, FALSE, FALSE, TRUE), stringsAsFactors = FALSE
       )
```
# Formatting Dates
```{r}
str(surveys)
# load lubridate 
library("lubridate")
# Let’s create a date object and inspect the structure:
my_date <- ymd("2015-01-01")
str(my_date)
# Now let’s paste the year, month, and day separately - we get the same result:
my_date <- ymd(paste("2015", "1", "1", sep = "-")) 
str(my_date)
 #Now we apply this function to the surveys dataset. Create a character vector from the year, month, and day columns of surveys using paste():
paste(surveys$year, surveys$month, surveys$day, sep = "-")
# This character vector can be used as the argument for ymd():
ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))
# The resulting Date vector can be added to surveys as a new column called date:
surveys$date <- ymd(paste(surveys$year, surveys$month, surveys$day, sep = "-"))
str(surveys) # notice the new column, with 'date' as the class
# Let’s make sure everything worked correctly. One way to inspect the new column is to use summary():
summary(surveys$date)
# Something went wrong: some dates have missing values. Let’s investigate where they are coming from.
missing_dates <- surveys[is.na(surveys$date), c("year", "month", "day")]
head(missing_dates)
# Why did these dates fail to parse? If you had to use these data for your analyses, how would you deal with this situation? "Lubridate will throw that error when attempting to parse dates that do not exist because of daylight savings time."

```
Application written in R [@RCoreTeam] using the Shiny framework [@Chang2015].
# References 


              
              
              






