---
title: "Lab3B"
author: "Margaret Hilliard"
date: "9/7/2020"
output: html_document
bibliography: /Users/margarethilliard/Desktop/Evolutionary_Genomics/genomics-course/data/references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, eval = FALSE)
```
# Data Manipulation using dplyr and tidyr
```{r}
install.packages("tidyverse")
## load the tidyverse packages, incl. dplyr
library("tidyverse")
surveys <- read_csv("data_raw/portal_data_joined.csv")
## inspect the data
str(surveys)
## preview the data
View(surveys)
```
# Selecting columns and filtering rows
```{r}
# select columns of a data frame, use select()
# The first argument to this function is the data frame (surveys), and the subsequent arguments are the columns to keep
select(surveys, plot_id, species_id, weight)
# To select all columns except certain ones, put a “-” in front of the variable to exclude it
select(surveys, -record_id, -species_id)
# To choose rows based on a specific criterion, use filter():
filter(surveys, year == 1995)
```
# Pipes 
```{r}
# With intermediate steps, you create a temporary data frame and use that as input to the next function, like this:
surveys2 <- filter(surveys, weight < 5)
surveys_sml <- select(surveys2, species_id, sex, weight)
# You can also nest functions (i.e. one function inside of another), like this:
surveys_sml <- select(filter(surveys, weight < 5), species_id, sex, weight)
# Pipes let you take the output of one function and send it directly to the next, which is useful when you need to do many things to the same dataset. Pipes in R look like %>%
surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)

# If we want to create a new object with this smaller version of the data, we can assign it a new name:
surveys_sml <- surveys %>%
  filter(weight < 5) %>%
  select(species_id, sex, weight)

surveys_sml
```
# Challenge 1
```{r}
# Using pipes, subset the surveys data to include animals collected before 1995 and retain only the columns year, sex, and weight.

surveys_old <- surveys %>%
  filter(year < 1995) %>%
  select(year, sex, weight)
```
# Mutate
```{r}
# To create a new column of weight in kg:
surveys %>%
  mutate(weight_kg = weight / 1000)
# You can also create a second new column based on the first new column within the same call of mutate():
surveys %>%
  mutate(weight_kg = weight / 1000,
         weight_lb = weight_kg * 2.2)
# If this runs off your screen and you just want to see the first few rows, you can use a pipe to view the head() of the data.
surveys %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
# The first few rows of the output are full of NAs, so if we wanted to remove those we could insert a filter() in the chain:
surveys %>%
  filter(!is.na(weight)) %>%
  mutate(weight_kg = weight / 1000) %>%
  head()
# is.na() is a function that determines whether something is an NA. The ! symbol negates the result, so we’re asking for every row where weight is not an NA.
```
# Challenge 2
```{r}
# Create a new data frame from the surveys data that meets the following criteria: contains only the species_id column and a new column called hindfoot_cm containing the hindfoot_length values converted to centimeters. In this hindfoot_cm column, there are no NAs and all values are less than 3.
surveys$hindfoot_length

surveys_cm <- surveys %>%
  filter(!is.na(hindfoot_length)) %>%
  mutate(hindfoot_cm = hindfoot_length / 10) %>%
  filter(hindfoot_cm < 3) %>%
  select(species_id, hindfoot_cm )

surveys_cm
```
# Split-apply-combine data analysis and the summarize() function
```{r}
# group_by() is often used together with summarize(), which collapses each group into a single-row summary of that group. group_by() takes as arguments the column names that contain the categorical variables for which you want to calculate the summary statistics. So to compute the mean weight by sex:

surveys %>%
  group_by(sex) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE))
#> `summarise()` ungrouping output (override with `.groups` argument)
# You can also group by multiple columns:
surveys %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight, na.rm = TRUE)) %>% 
  tail()
#> `summarise()` regrouping output by 'sex' (override with `.groups` argument)

# Because the missing values are removed first, we can omit na.rm = TRUE when computing the mean:
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight))
#> `summarise()` regrouping output by 'sex' (override with `.groups` argument)

surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight)) %>%
  print(n = 15)

# Once the data are grouped, you can also summarize multiple variables at the same time (and not necessarily on the same variable). For instance, we could add a column indicating the minimum weight for each species for each sex:
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight))

# It is sometimes useful to rearrange the result of a query to inspect the values. For instance, we can sort on min_weight to put the lighter species first:

surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(min_weight)

# To sort in descending order, we need to add the desc() function. If we want to sort the results by decreasing order of mean weight:
surveys %>%
  filter(!is.na(weight)) %>%
  group_by(sex, species_id) %>%
  summarize(mean_weight = mean(weight),
            min_weight = min(weight)) %>%
  arrange(desc(mean_weight))

```
# Counting
```{r}
# if we wanted to count the number of rows of data for each sex, we would do:
surveys %>%
    count(sex) 

# surveys %>% count() is equivalent to:
surveys %>%
    group_by(sex) %>%
    summarise(count = n())

# For convenience, count() provides the sort argument:
surveys %>%
    count(sex, sort = TRUE) 
# If we wanted to count combination of factors, such as sex and species, we would specify the first and the second factor as the arguments of count():

surveys %>%
  count(sex, species) 
# we can proceed with arrange() to sort the table according to a number of criteria so that we have a better comparison. For instance, we might want to arrange the table above in (i) an alphabetical order of the levels of the species and (ii) in descending order of the count:

surveys %>%
  count(sex, species) %>%
  arrange(species, desc(n))
```
# Challenge 3
```{r}
# How many animals were caught in each plot_type surveyed?
surveys %>%
    count(plot_type, sort = TRUE) 

# Use group_by() and summarize() to find the mean, min, and max hindfoot length for each species (using species_id). Also add the number of observations (hint: see ?n).
?n

surveys %>%
  filter(!is.na(hindfoot_length)) %>%
  group_by(species_id) %>%
  summarize(mean_foot = mean(hindfoot_length),
            min_foot = min(hindfoot_length), 
            max_foot = max(hindfoot_length), n = n())

# What was the heaviest animal measured in each year? Return the columns year, genus, species_id, and weight

surveys %>%
  filter(!is.na(weight)) %>%
  group_by(year) %>%
  filter(weight == max(weight)) %>%
  select(year, genus, species, weight) %>%
  arrange(year)
```
# Reshaping with gather and spread
```{r}
# Let’s use spread() to transform surveys to find the mean weight of each genus in each plot over the entire survey period. We use filter(), group_by() and summarise() to filter our observations and variables of interest, and create a new variable for the mean_weight.
surveys_gw <- surveys %>%
  filter(!is.na(weight)) %>%
  group_by(plot_id, genus) %>%
  summarize(mean_weight = mean(weight))
str(surveys_gw)
# This yields surveys_gw where the observations for each plot are spread across multiple rows, 196 observations of 3 variables. Using spread() to key on genus with values from mean_weight this becomes 24 observations of 11 variables, one row for each plot.
surveys_spread <- surveys_gw %>%
  spread(key = genus, value = mean_weight)

str(surveys_spread)
# fill in the missing values 
surveys_gw %>%
  spread(genus, mean_weight, fill = 0) %>%
  head()
```
# Gathering 
```{r}
surveys_gather <- surveys_spread %>%
  gather(key = "genus", value = "mean_weight", -plot_id)

str(surveys_gather)
# if the columns are directly adjacent, we don’t even need to list them all out - just use the : operator!
surveys_spread %>%
  gather(key = "genus", value = "mean_weight", Baiomys:Spermophilus) %>%
  head()
```
# Challenge 4
```{r}
# 1. Spread the surveys data frame with year as columns, plot_id as rows, and the number of genera per plot as the values. You will need to summarize before reshaping, and use the function n_distinct() to get the number of unique genera within a particular chunk of data. It’s a powerful function! See ?n_distinct for more.
surveys_spread <- surveys %>%
  group_by(plot_id, year) %>%
  summarize(n_genera = n_distinct(genus)) %>%
  spread(year, n_genera)
# 2. Now take that data frame and gather() it again, so each row is a unique plot_id by year combination.
surveys_spread %>%
  gather("year", "n_genera", -plot_id)

# 3. The surveys data set has two measurement columns: hindfoot_length and weight. This makes it difficult to do things like look at the relationship between mean values of each measurement per year in different plot types. Let’s walk through a common solution for this type of problem. First, use gather() to create a dataset where we have a key column called measurement and a value column that takes on the value of either hindfoot_length or weight. Hint: You’ll need to specify which columns are being gathered.

surveys_long <- surveys %>%
  gather("measurement", "value", hindfoot_length, weight)
# 4. With this new data set, calculate the average of each measurement in each year for each different plot_type. Then spread() them into a data set with a column for hindfoot_length and weight. Hint: You only need to specify the key and value columns for spread().

surveys_long %>%
  group_by(year, measurement, plot_type) %>%
  summarize(mean_value = mean(value, na.rm=TRUE)) %>%
  spread(measurement, mean_value)
```
# Exporting data 
```{r}
# Let’s start by removing observations of animals for which weight and hindfoot_length are missing, or the sex has not been determined:

surveys_complete <- surveys %>%
  filter(!is.na(weight),           # remove missing weight
         !is.na(hindfoot_length),  # remove missing hindfoot_length
         !is.na(sex))                # remove missing sex

# Because we are interested in plotting how species abundances have changed through time, we are also going to remove observations for rare species (i.e., that have been observed less than 50 times). We will do this in two steps: first we are going to create a data set that counts how often each species has been observed, and filter out the rare species; then, we will extract only the observations for these more common species:

## Extract the most common species_id
species_counts <- surveys_complete %>%
    count(species_id) %>% 
    filter(n >= 50)

## Only keep the most common species
surveys_complete <- surveys_complete %>%
  filter(species_id %in% species_counts$species_id)
# To make sure that everyone has the same data set, check that surveys_complete has 30463 rows and 13 columns by typing:
dim(surveys_complete)
# Now that our data set is ready, we can save it as a CSV file in our data folder.
write_csv(surveys_complete, path = "data/surveys_complete.csv")
```
Application written in R [@RCoreTeam] using the Shiny framework [@Chang2015].
# References 

