---
title: "lab6ex"
author: "Margaret Hilliard"
date: "9/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Exercises

### For the above graph “World COVID-19 Confirmed case” summarize the counts for each Country on the graph and update the graph to 9/26/2020. You may need to adjust the size of the points.

import case data from 9/26/20
```{r}
report_09_26_2020 <- read_csv(url("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports/09-26-2020.csv")) %>% 
  rename(Long = "Long_") %>%
  group_by(Country_Region) %>%
  summarize(Confirmed = sum(Confirmed), Lat, Long)

head(report_09_26_2020)
```


```{r}
# map_data
world <- map_data("world")

world_join <- left_join(world, report_09_26_2020, by = c("region" = "Country_Region"))

ggplot(world_join, aes(x = Long, y = Lat, size = Confirmed)) +
    borders("world", colour = "white", fill = "grey90") +
    geom_polygon(data = world_join, aes(fill = Confirmed)) 





    theme_bw() +
    geom_polygon(data = report_09_26_2020, aes(fill = Confirmed)) +
   scale_fill_gradientn(colours = 
                         wes_palette("Zissou1", 100, type = "continuous"), +
  labs(title = "Worldwide COVID-19 Confirmed Cases")
  

  geom_point(data = report_09_26_2020, aes(x = Long, y = Lat, size = Confirmed, color = Confirmed, alpha = 0.5)) + 
  labs(title = "Worldwide COVID-19 Confirmed Cases", x = '', y = '', size = "Cases") +
  coord_fixed(ratio = 1.5) 


    labs(title = 'World COVID-19 Confirmed cases',x = '', y = '',
        size="Cases") +
    theme(legend.position = "right") +
    coord_fixed(ratio=1.5) 
```

